I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    j "My name is John, Jameston John.... {p=1.0}At your service."
  File "game/script.rpy", line 8, in callbackJJ
    renpy.music.play("robot_2.ogg",channel="sounds", loop = False)
Exception: Audio channel 'sounds' is unknown.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    j "My name is John, Jameston John.... {p=1.0}At your service."
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\character.py", line 1394, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\character.py", line 1045, in do_display
    display_say(who,
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\character.py", line 632, in display_say
    c("show", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 8, in callbackJJ
    renpy.music.play("robot_2.ogg",channel="sounds", loop = False)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\audio\music.py", line 103, in play
    c = get_channel(channel)
  File "C:\Users\lesli\OneDrive\Desktop\renpy-8.2.3-sdk\renpy\audio\audio.py", line 922, in get_channel
    raise Exception("Audio channel %r is unknown." % name)
Exception: Audio channel 'sounds' is unknown.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Pathfinding My Way To Your Heart 1.0
Sun Jul 14 01:06:34 2024
